apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy69
  labels:
    app: autodeploy69
  namespace: namespace-workflow-1708427320393
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy69
  template:
    metadata:
      labels:
        app: autodeploy69
    spec:
      containers:
        - name: autodeploy69
          image: acrworkflow1708427320393.azurecr.io/image-workflow-1708427320393:latest
          ports:
            - containerPort: 5000